web:
  image: nginx
  volumes:
   - ./hypervisor_etc:/etc/nginx/conf.d/hypervisor_etc
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/hypervisor_etc > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
